### ISSUE TITLE
Not able to run tsqllint in Docker container

### ISSUE THREAD

**Issue by simonmulser** [tsqllint/tsqllint#178]
Docker file:
```
FROM node:9.11.1-alpine

WORKDIR /data

RUN yarn global add tsqllint

# RUN npm install tsqllint -g
```

Build file with `docker build -t sql-test .` and run it with `docker run -it sql-test tsqllint --help` fails with:
```
events.js:165
      throw er; // Unhandled 'error' event
      ^

Error: spawn /usr/local/share/.config/yarn/global/node_modules/tsqllint/assemblies/linux-x64/TSQLLint.Console ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:201:19)
    at onErrorNT (internal/child_process.js:379:16)
    at process._tickCallback (internal/process/next_tick.js:178:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:697:11)
    at startup (internal/bootstrap/node.js:201:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:516:3)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:207:12)
    at onErrorNT (internal/child_process.js:379:16)
    [... lines matching original stack trace ...]
    at bootstrapNodeJSCore (internal/bootstrap/node.js:516:3)
```

Any ideas why?

Additional output:
Using `RUN npm install tsqllint -g` fails with:
```

events.js:165
      throw er; // Unhandled 'error' event
      ^

Error: EACCES: permission denied, open 'linux-x64.tgz'
Emitted 'error' event at:
    at fs.open (fs.js:2225:12)
    at FSReqWrap.oncomplete (fs.js:153:20)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tsqllint@1.10.1 install: `node ./scripts/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the tsqllint@1.10.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-04-28T12_49_38_315Z-debug.log
```

`docker run -it sql-test node --version`: `v9.11.1`
`docker run -it sql-test npm --version`: `5.6.0`
`docker run -it sql-test yarn --version`: `1.5.1`

**Comment by nathan-boyd** [comment]
during npm install we.run /scripts/install.js there we detect operating system type, and then pull down the appropriate assembly. This error reads like node doesn't have permission to untar that assembly after download. 

Is there a way to run this line in the Docker file with elevated privileges?

**Comment by simonmulser** [comment]
The alpine linux caused the error. This is a working Dockerfile:
```
FROM node:9.11.1

WORKDIR /data

RUN apt-get update && apt-get install libunwind8

RUN yarn global add tsqllint
```

Additionally I had to install `libunwind8` (as in the `travis.yml` of this project).

**Comment by nathan-boyd** [comment]
Thanks for providing the update to the Dockerfile, and for your interest in this tool!
