### ISSUE TITLE
[DEP0013] Yarn Install Fails in Visual Studio Build System

### ISSUE THREAD

**Issue by candersonadig** [tsqllint/tsqllint#194]
This is the output.   I'm not certain it is related to tsqllint but it is the first I've ever seen this.

2018-06-15T20:30:50.7055082Z yarn install v1.6.0
2018-06-15T20:30:50.9602404Z [1/4] Resolving packages...
2018-06-15T20:31:00.7329988Z [2/4] Fetching packages...
2018-06-15T20:31:05.2172599Z info fsevents@1.2.4: The platform "win32" is incompatible with this module.
2018-06-15T20:31:05.2174908Z info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
2018-06-15T20:31:05.3049501Z [3/4] Linking dependencies...
2018-06-15T20:31:22.2247937Z [4/4] Building fresh packages...
2018-06-15T20:31:37.4545000Z error F:\BuildAgents\vsts-agent-win-1\_work\6\s\Web\node_modules\tsqllint: Command failed.
2018-06-15T20:31:37.4545436Z info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
2018-06-15T20:31:37.4810217Z Exit code: 1
2018-06-15T20:31:37.4823018Z Command: node ./scripts/install.js
2018-06-15T20:31:37.4823310Z Arguments: 
2018-06-15T20:31:37.4823520Z Directory: F:\BuildAgents\vsts-agent-win-1\_work\6\s\Web\node_modules\tsqllint
2018-06-15T20:31:37.4823729Z Output:
2018-06-15T20:31:37.4823945Z (node:8876) [DEP0013] DeprecationWarning: Calling an asynchronous function without callback is deprecated.
2018-06-15T20:31:37.4824249Z { Error: getaddrinfo EAI_AGAIN github-production-release-asset-2e65be.s3.amazonaws.com:443
2018-06-15T20:31:37.4824514Z     at Object._errnoException (util.js:1022:11)
2018-06-15T20:31:37.4824748Z     at errnoException (dns.js:55:15)
2018-06-15T20:31:37.4824955Z     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)
2018-06-15T20:31:37.4825171Z   code: 'EAI_AGAIN',
2018-06-15T20:31:37.4825335Z   errno: 'EAI_AGAIN',
2018-06-15T20:31:37.4825518Z   syscall: 'getaddrinfo',
2018-06-15T20:31:37.4825731Z   hostname: 'github-production-release-asset-2e65be.s3.amazonaws.com',
2018-06-15T20:31:37.4825977Z   host: 'github-production-release-asset-2e65be.s3.amazonaws.com',
2018-06-15T20:31:37.4826163Z   port: 443 }
2018-06-15T20:31:37.5618388Z ##[error]Process completed with exit code 1.

**Comment by candersonadig** [comment]
I think this may be unrelated connectivity issues.

**Comment by nathan-boyd** [comment]
That seems correct. The install script pulls the TSQLLint package for your runtime from the latest Github release. This reads like the runtime failed to download because Github couldn't access its AWS S3 backend.
