### ISSUE TITLE
npm install does not work: "ERR_INVALID_CALLBACK"

### ISSUE THREAD

**Issue by thegoatherder** [tsqllint/tsqllint#237]
I've tried to install this with:
```
npm i -g tsqllint
yarn add global tsqllint
```
Both result in error: `[ERR_INVALID_CALLBACK]: Callback must be a function. Received undefined`:

```
PS G:\Repos\somerepo> npm i tsqllint -g
c:\luna\etc\.npm\global\tsqllint -> c:\luna\etc\.npm\global\node_modules\tsqllint\tsqllint.js

> tsqllint@1.11.0 install c:\luna\etc\.npm\global\node_modules\tsqllint
> node ./scripts/install.js

fs.js:152
    throw new ERR_INVALID_CALLBACK(cb);
    ^

TypeError [ERR_INVALID_CALLBACK]: Callback must be a function. Received undefined
    at makeCallback (fs.js:152:11)
    at Object.unlink (fs.js:1042:14)
    at RedirectableRequest.<anonymous> (c:\luna\etc\.npm\global\node_modules\tsqllint\scripts\install.js:54:14)
    at RedirectableRequest.emit (events.js:310:20)
    at ClientRequest.eventHandlers.<computed> (c:\luna\etc\.npm\global\node_modules\tsqllint\node_modules\follow-redirects\index.js:13:24)
    at ClientRequest.emit (events.js:310:20)
    at TLSSocket.socketErrorListener (_http_client.js:426:9)
    at TLSSocket.emit (events.js:310:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3) {
  code: 'ERR_INVALID_CALLBACK'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tsqllint@1.11.0 install: `node ./scripts/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the tsqllint@1.11.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\SomeUser\AppData\Roaming\npm-cache\_logs\2020-05-14T11_28_50_398Z-debug.log
```

I've confirmed that other npm packages install normally on the same machine and same folder:

```
PS G:\Repos\somerepo> npm i compromise
npm notice created a lockfile as package-lock.json. You should commit this file.
+ compromise@13.2.0
added 2 packages from 1 contributor and audited 2 packages in 1.044s
found 0 vulnerabilities
```

**Comment by nathan-boyd** [comment]
what version of Node and NPM are you running?

**Comment by thegoatherder** [comment]
```
PS > node --version
v12.16.2
PS > npm --version
6.14.4
```
