### ISSUE TITLE
TSQLLint --fix error than using 'OR REPLACE' syntax

### ISSUE THREAD

**Issue by kaay-it** [tsqllint/tsqllint#337]
Hi
When I'm using command like `tsqllint -x <file>.sql` I getting the error.
<details>
<summary>TSQLLint Output</summary>

```text
% tsqllint -x HISTORY.sql 
running tsqllint
HISTORY.sql(456,4): warning semicolon-termination : Statement not terminated with semicolon.
HISTORY.sql(35,45): warning semicolon-termination : Statement not terminated with semicolon.
HISTORY.sql(37,136): warning semicolon-termination : Statement not terminated with semicolon.
HISTORY.sql(39,103): warning semicolon-termination : Statement not terminated with semicolon.
HISTORY.sql(40,103): warning semicolon-termination : Statement not terminated with semicolon.
HISTORY.sql(41,101): warning semicolon-termination : Statement not terminated with semicolon.
HISTORY.sql(43,111): warning semicolon-termination : Statement not terminated with semicolon.
HISTORY.sql(44,117): warning semicolon-termination : Statement not terminated with semicolon.
HISTORY.sql(45,115): warning semicolon-termination : Statement not terminated with semicolon.
HISTORY.sql(48,66): warning semicolon-termination : Statement not terminated with semicolon.
HISTORY.sql(51,106): warning semicolon-termination : Statement not terminated with semicolon.
HISTORY.sql(54,78): warning semicolon-termination : Statement not terminated with semicolon.
HISTORY.sql(55,79): warning semicolon-termination : Statement not terminated with semicolon.
HISTORY.sql(56,88): warning semicolon-termination : Statement not terminated with semicolon.
HISTORY.sql(57,85): warning semicolon-termination : Statement not terminated with semicolon.
HISTORY.sql(59,92): warning semicolon-termination : Statement not terminated with semicolon.
HISTORY.sql(60,75): warning semicolon-termination : Statement not terminated with semicolon.
HISTORY.sql(62,84): warning semicolon-termination : Statement not terminated with semicolon.
HISTORY.sql(65,34): warning semicolon-termination : Statement not terminated with semicolon.
HISTORY.sql(128,26): warning semicolon-termination : Statement not terminated with semicolon.
HISTORY.sql(187,30): warning semicolon-termination : Statement not terminated with semicolon.
HISTORY.sql(436,28): warning semicolon-termination : Statement not terminated with semicolon.
HISTORY.sql(453,30): warning semicolon-termination : Statement not terminated with semicolon.
HISTORY.sql(455,32): warning semicolon-termination : Statement not terminated with semicolon.
HISTORY.sql(1,1): warning set-quoted-identifier : Expected SET QUOTED_IDENTIFIER ON near top of file.
HISTORY.sql(1,1): warning set-transaction-isolation-level : Expected SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED near top of file.
HISTORY.sql(43,2): warning set-variable : Expected variable to be set using SELECT statement.
HISTORY.sql(44,5): warning set-variable : Expected variable to be set using SELECT statement.
HISTORY.sql(45,5): warning set-variable : Expected variable to be set using SELECT statement.
HISTORY.sql(48,3): warning set-variable : Expected variable to be set using SELECT statement.
HISTORY.sql(51,3): warning set-variable : Expected variable to be set using SELECT statement.
HISTORY.sql(54,2): warning set-variable : Expected variable to be set using SELECT statement.
HISTORY.sql(55,2): warning set-variable : Expected variable to be set using SELECT statement.
HISTORY.sql(56,2): warning set-variable : Expected variable to be set using SELECT statement.
HISTORY.sql(57,2): warning set-variable : Expected variable to be set using SELECT statement.
HISTORY.sql(59,2): warning set-variable : Expected variable to be set using SELECT statement.
HISTORY.sql(60,2): warning set-variable : Expected variable to be set using SELECT statement.
HISTORY.sql(62,2): warning set-variable : Expected variable to be set using SELECT statement.
TSQLLint encountered a problem.
System.Exception: Parsing failed. Incorrect syntax near CREATE.. Incorrect syntax near OR.
   at TSQLLint.Common.FixHelpers.FindNodes[T](List`1 fileLines, Func`2 where)
   at TSQLLint.Infrastructure.Rules.BaseNearTopOfFileRule.FixViolation(List`1 fileLines, IRuleViolation ruleViolation, FileLineActions actions) in /root/project/source/TSQLLint.Infrastructure/Rules/Common/BaseNearTopOfFileRule.cs:line 29
   at TSQLLint.Infrastructure.Parser.ViolationFixer.Fix() in /root/project/source/TSQLLint.Infrastructure/Parser/ViolationFixer.cs:line 34
   at TSQLLint.Application.Run() in /root/project/source/TSQLLint/Application.cs:line 88
   at TSQLLint.Program.Main(String[] args) in /root/project/source/TSQLLint/Program.cs:line 18
kalininaleksey@MAC-Kalinin-A StoredProcedures % 
```

</details>

I think the problem is raising in line `CREATE OR ALTER PROCEDURE .....` in file.

<details>

<summary>My .tsqllintrc file</summary>

```json
{
    "rules": {
        "semicolon-termination": "warning",
        "set-ansi": "warning",
        "set-nocount": "warning",
        "set-quoted-identifier": "warning",
        "set-transaction-isolation-level": "warning",
        "set-variable": "warning"
    },
    "compatibility-level": 150
}
```

</details>

**Comment by kaay-it** [comment]
Oh, sorry, tsqllint version:
```text
% tsqllint -v
running tsqllint
v1.15.3.0
```
