### ISSUE TITLE
Crash when given a path to a non-existent directory

### ISSUE THREAD

**Issue by dougwilson** [tsqllint/tsqllint#38]
```
> tsqllint C:\BogusDir\BogusFile.sql
```

A Windows application crash dialog box opens, the following is on the console:

```
Unhandled Exception: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\BogusDir'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.Directory.EnumerateFiles(String path, String searchPattern, SearchOption searchOption)
   at System.IO.Abstractions.DirectoryWrapper.EnumerateFiles(String path, String searchPattern, SearchOption searchOption)
   at TSQLLINT_LIB.Parser.SqlFileProcessor.ProcessWildCard(String path) in d:\git\tsqllint\TSQLLINT_LIB\Parser\SqlFileProcessor.cs:line 109
   at TSQLLINT_LIB.Parser.SqlFileProcessor.ProcessPath(String path) in d:\git\tsqllint\TSQLLINT_LIB\Parser\SqlFileProcessor.cs:line 58
   at TSQLLINT_LIB.Parser.SqlFileProcessor.ProcessList(List`1 paths) in d:\git\tsqllint\TSQLLINT_LIB\Parser\SqlFileProcessor.cs:line 129
   at TSQLLINT_CONSOLE.LintingHandler.Lint()
   at TSQLLINT_CONSOLE.Application.Run()
   at TSQLLINT_CONSOLE.Program.Main(String[] args)
```

**Comment by nathan-boyd** [comment]
was able to reproduce
