### ISSUE TITLE
Concat strings rule Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by nathan-boyd** [tsqllint/tsqllint#88]
```
Object reference not set to an instance of an object.
   at TSQLLint.Lib.Rules.ConcatStringsRule.Visit(DeclareVariableElement node)
   at Microsoft.SqlServer.TransactSql.ScriptDom.TSqlFragmentVisitor.ExplicitVisit(DeclareVariableElement node)
   at Microsoft.SqlServer.TransactSql.ScriptDom.DeclareVariableStatement.AcceptChildren(TSqlFragmentVisitor visitor)
   at Microsoft.SqlServer.TransactSql.ScriptDom.TSqlBatch.AcceptChildren(TSqlFragmentVisitor visitor)
   at Microsoft.SqlServer.TransactSql.ScriptDom.TSqlScript.AcceptChildren(TSqlFragmentVisitor visitor)
   at TSQLLint.Lib.Parser.SqlRuleVisitor.VisitRules(String sqlPath, Stream sqlFileStream)
   at TSQLLint.Lib.Parser.SqlFileProcessor.ProcessRules(Stream fileStream, String filePath)
   at TSQLLint.Lib.Parser.SqlFileProcessor.ProcessFile(Stream fileStream, String filePath)
   at TSQLLint.Lib.Parser.SqlFileProcessor.ProcessIfSqlFile(String fileName)
   at TSQLLint.Lib.Parser.SqlFileProcessor.ProcessDirectory(String path)
   at TSQLLint.Lib.Parser.SqlFileProcessor.ProcessPath(String path)
   at TSQLLint.Lib.Parser.SqlFileProcessor.ProcessList(List`1 paths)
   at TSQLLint.Console.Application.Run()
   at TSQLLint.Console.Program.Main(String[] args)
```

Removing this rule from default configs until issue is resolved

**Comment by geoffbaker** [comment]
Rule should have been removed and replaced with new rule only checking for unicode characters in a non unicode string (e.g. one with N prefix)
